# Generated by Django 2.2.3 on 2019-07-05 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('notes', models.TextField(max_length=1000)),
                ('info', models.TextField(default='A happy little course', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('reminder_type', models.CharField(choices=[('A', 'Assignment'), ('M', 'Meet up'), ('S', 'Study'), ('T', 'Test')], max_length=40)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('total', models.FloatField(default=100)),
                ('received', models.FloatField(default=0)),
                ('weight', models.FloatField(default=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reminders.Course')),
            ],
        ),
    ]
