# Generated by Django 2.2.3 on 2019-07-19 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('notes', models.TextField(max_length=1000)),
                ('info', models.TextField(default='A happy little course', max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('reminder_type', models.CharField(choices=[('Assignment', 'A'), ('Meet up', 'M'), ('Study', 'S'), ('Test', 'T')], max_length=40)),
                ('due_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('total', models.FloatField(default=100)),
                ('received', models.FloatField(default=0)),
                ('weight', models.FloatField(default=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_reminders', to='reminders.Course')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
