# Generated by Django 2.2.3 on 2019-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(blank=True, default='A happy little course', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
