# Generated by Django 2.2.3 on 2019-08-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_auto_20190803_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='category',
            field=models.CharField(choices=[('Assignment', 'A'), ('Test', 'T'), ('Other', 'O')], max_length=40, null=True),
        ),
    ]
