export const GET_REMINDERS = 'GET_REMINDERS';
export const DELETE_REMINDERS = 'DELETE_REMINDERS';
export const ADD_REMINDERS = 'ADD_REMINDERS';
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE'