
// CONTENT 
export const GET_REMINDERS = 'GET_REMINDERS';
export const DELETE_REMINDERS = 'DELETE_REMINDERS';
export const ADD_REMINDERS = 'ADD_REMINDERS';
export const GET_COURSES = 'GET_COURSES';
export const DELETE_COURSES = 'DELETE_COURSES';
export const ADD_COURSES = 'ADD_COURSES';

// ERRORS 
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

// NAVIGATION
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';
export const SELECT_ACTIVE = 'SELECT_ACTIVE';
export const UPDATE_WINDOW = 'UPDATE_WINDOW';

// AUTHENTIFICATION 
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";